{
 "title": "Test Dashboard",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "author", "query": "SELECT id from users" }
  ]
 },
 "panels": [
  {
   "title": "Another Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, creation_date, intro, title, author FROM stories WHERE author IN ( $author  )"
    }
   ]
  },
  {
   "title": "Test Panel",
   "type": "table",
   "description": "TEST DESC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, display_name, last_access, registration_date FROM users WHERE id IN ( $author  )"
    }
   ]
  },
  {
   "title": "Panel With joins",
   "type": "table",
   "description": "Join users and stories",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT author, \r\ndisplay_name, \r\nlast_access, \r\nregistration_date, \r\nstories.id as story_id, \r\ncreation_date, \r\nintro, \r\ntitle  \r\nFROM users JOIN stories on users.id = stories.author\r\nWHERE stories.author IN ( $author  ) "
    }
   ]
  },
  {
   "title": "Stories per User",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT count(id) as stories, author from stories \r\nWHERE author IN ( $author  )\r\nGROUP BY author"
    }
   ]
  }
 ]
}